name: "Home Assistant AI Helper"
slug: "ha_ai_helper"
description: "Lightweight and secure AI agent companion for Home Assistant"
version: "0.5.1"
image: "ghcr.io/sserhii-tech/ha-mcp-helper-{arch}"
arch:
  - "aarch64"
  - "amd64"
init: false
map:
  - "homeassistant_config:rw"
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "AI Helper REST API"
options:
  api_key: ""
schema:
  api_key: "str"
